# the building container
FROM maven:3-eclipse-temurin-8 AS builder

RUN mkdir -p /tmp/pia
COPY . /tmp/pia/
RUN mvn -f /tmp/pia/pom.xml -Dmaven.test.skip --settings /tmp/pia/.mvn/unblock-mirrors.xml package


# start the real container
FROM eclipse-temurin:8-jre-focal

LABEL MAINTAINERS="Julian Uszkoreit <julian.uszkoreit@rub.de>"\
      description="Docker image for command line execution of PIA - Protein Inference Algorithms"

# prepare zip and wget
RUN apt-get update; \
    apt-get install -y unzip wget; \
    apt-get clean

#preparing directories
RUN mkdir -p /data/in; mkdir -p /data/out; mkdir -p /opt/pia;

# copy just build PIA zip and uncompress
COPY --from=builder /tmp/pia/target/pia*.zip /opt/pia/pia.zip
RUN cd /opt/pia; \
    unzip pia.zip; \
    rm pia.zip; \
    mv pia*.jar pia.jar;

# cleanup
RUN apt-get remove -y unzip wget;

ENTRYPOINT ["java", "-jar", "/opt/pia/pia.jar"]
CMD ["--help"]
